### ISSUE TITLE
Modify Cryptol to SAWCore translation to avoid using ad-hoc-polymorphic functions

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol-verifier#1]
Non-parametric polymorphic SAWCore functions like `eq`, `zero`, `binary`, and `comparison` are not nice: They don't work on all the type instances they claim to, and they require custom code in the rewriter, typechecker, and simulation/evaluation backends. It is better to use operations that can be evaluated with the usual pattern-matching mechanism.

The plan is to essentially revert changeset 172a7ff3. We will reintroduce a datatype `KType` that syntactically encodes a Cryptol type expression, as well as the meaning function `ty : KType -> sort 0`. The change will require a nested encoding for tuples and records in SAWCore, so we are currently blocked on GaloisInc/saw-core#6.

**Comment by robdockins** [comment]
I think we fixed this some time ago via explicit dictionary construction, yes?

**Comment by brianhuffman** [comment]
Indeed, this was fixed in Dec 2018 by 606c2f97e45abe5da02aa6d678a59aac64f92031.
