### ISSUE TITLE
Fix breakages due to new Cryptol evaluator

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol-verifier#3]

**Comment by kiniry** [comment]
My, that's vague...

**Comment by robdockins** [comment]
This should now be fixed via c657363f51f5159c4a04da90429de7531d280914 and GaloisInc/saw-script@40b3a5a3b1c8a82625f119bd7df0306bdd92ffab

The fixes mostly involved minor tweaks to track API changes in Cryptol.  The most disruptive change was that the Cryptol term pretty-printer now lives in the IO monad instead of being a pure function; this required a small amount of refactoring.
