### ISSUE TITLE
Translation fails for parameterized records

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol-verifier#4]
Running the ECDSA proof from the `saw-script` repository results in the following error from `saw`:

````
saw: user error (proveProp: Cmp (ec_point_ops::JacobianPoint a`2540))
````

The `proveProp` function appears to implement a translation for `Cmp` on records, but perhaps doesn't handle the case where the type is parameterized?

**Comment by brianhuffman** [comment]
Fixed in 841931ffe8bbbf733ba25b52c2507a7a0768a95a.
