### ISSUE TITLE
propagate new "int-modulo" type into cryptol-verifier

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol-verifier#5]
We're currently missing code for translating `TCIntMod` types and `TVIntMod` values.

**Comment by robdockins** [comment]
I suppose the related primitives and class instances must also be translated.

**Comment by brianhuffman** [comment]
We'll need to add some support for type `Z n` to saw-core before we can implement this properly.

**Comment by robdockins** [comment]
This was implemented at some point, I think...
